spring.application.name=oboticario-revenda

admin.username=${ADMIN_USER}
admin.password=${ADMIN_PASSWORD}
remember.me=${REMEMBER_ME}
spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB

imagekit.public=${IMAGEKIT_PUBLIC}
imagekit.private=${IMAGEKIT_PRIVATE}

spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=oboticario-revenda