spring.application.name=oboticario-revenda

admin.username=${ADMIN_USER}
admin.password=${ADMIN_PASSWORD}
remember.me=${REMEMBER_ME}
spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB

imagekit.private=${IMAGEKIT_PRIVATE}

spring.data.mongodb.uri=${MONGO_URL}
spring.data.mongodb.database=oboticario-revenda